### ISSUE TITLE
IAD/AdMob/Flurry precedence and priority.  (fallback solutions)

### ISSUE THREAD

**Issue by djett41** [floatinghotpot/cordova-plugin-iad#20]
Hello, Great plugins by the way!  I am trying to implement a solution in which 
1.  For ios you can fallback on  AdMob if IAD doesnt fill, and if Admob doesnt fill you can fallback on flurry (using all 3).  
2.  For android you would use AdMob as a primary, but fallback on Flurry if Admob isnt filled.

My question is what is the best practice for implementing this?  I have tried hiding/showing based on the recieveAd and fail to recieve ad events but the behavior is inconsistent.  For example, when IAD ads were available again, calling show(true) would not replace the Admob or Flurry ad although I could see successful receive events being fired.

Any idea on how you could accomplish this for this plugin?  

Thanks

**Comment by DamiJegede** [comment]
I didn't see any way to implement mediation in the docs. The doc only says this is possible. Could you kindly update the doc to include a mediation how-to, or point us in the right direction?

**Comment by floatinghotpot** [comment]
please read the doc here:
https://github.com/floatinghotpot/cordova-admob-pro

Optional mediations to increase your revenue (Read about [AdMob Mediation Networks](https://developers.google.com/mobile-ads-sdk/docs/admob/android/mediation-networks)):
