### ISSUE TITLE
Reference Error: Can't find variable iAd

### ISSUE THREAD

**Issue by codyhawke** [floatinghotpot/cordova-plugin-iad#23]
Hi - I'm trying to get this plugin going on my phone app. When I try to create an ad, I get a JS reference error: Can't find variable iAd.
In my config.xml, I have:
<gap:plugin name="com.rjfun.cordova.plugin.iad" version="0.1.0" />
In my app, I have
if(iAd) {
			iAd.createBanner( {
    position:iAd.AD_POSITION.BOTTOM_CENTER, 
    autoShow:true
} );	
}
Any idea what could be going on? Thanks.

**Comment by floatinghotpot** [comment]
## Notice

This plugin will not be updated any more.

Please use the pro version instead, which is much better and supports both banner and interstitial iAd.
- git repo: [https://github.com/floatinghotpot/cordova-iad-pro](https://github.com/floatinghotpot/cordova-iad-pro)
- plugin id: `com.rjfun.cordova.iad`
