### ISSUE TITLE
wrong webview height

### ISSUE THREAD

**Issue by duseless** [floatinghotpot/cordova-plugin-iad#24]
the line 153  in CDViAd.m   wf.size.height = bf.origin.y;  needs to be changed to    wf.size.height = bf.origin.y - top;

**Comment by floatinghotpot** [comment]
## Notice

This plugin will not be updated any more.

Please use the pro version instead, which is much better and supports both banner and interstitial iAd.
- git repo: [https://github.com/floatinghotpot/cordova-iad-pro](https://github.com/floatinghotpot/cordova-iad-pro)
- plugin id: `com.rjfun.cordova.iad`
