### ISSUE TITLE
writeJavascript deprecated

### ISSUE THREAD

**Issue by ppdev1** [floatinghotpot/cordova-plugin-iad#25]
Hi,

Thanks for a great plugin!

I am however experiencing an issues Im hoping to get some help with. When I use "showAd(true)" and "showAd(false)" it all works as intended, but, sometimes, with no user-interaction the iAd just decides to show up. Following can then be seen in the log:

2014-12-16 21:35:23.592  Banner failed to load Ad
2014-12-16 21:35:24.798  Banner Ad loaded
2014-12-16 21:35:24.798  CDViAd Show Ad: 1
2014-12-16 21:35:24.803  banner visible

Could it maybe be related to the following Depcrecation Warnings in Xcode? 

"'writeJavascript:' is deprecated: Deprecated in Cordova 3.6. Use the CDVCommandDelegate equivalent of evalJs:. This will be removed in 4.0.0" 

I assume its the same issue as in https://github.com/floatinghotpot/cordova-plugin-admob/issues/169

Any help/tips would be appreciated!

Thanks!

**Comment by floatinghotpot** [comment]
## Notice

This plugin will not be updated any more.

Please use the pro version instead, which is much better and supports both banner and interstitial iAd.
- git repo: [https://github.com/floatinghotpot/cordova-iad-pro](https://github.com/floatinghotpot/cordova-iad-pro)
- plugin id: `com.rjfun.cordova.iad`
