### ISSUE TITLE
Ad pushing webview up

### ISSUE THREAD

**Issue by vespino** [floatinghotpot/cordova-plugin-iad#26]
Any idea why this is happening?

![image](https://cloud.githubusercontent.com/assets/6991325/5784053/01732320-9dc9-11e4-87ba-9e085739139b.jpg)

Using Phonegap Build by the way.

Also when using this plugin, the app seems to crash sometimes on start up.

**Comment by floatinghotpot** [comment]
i suggest you use the pro version: 
https://github.com/floatinghotpot/cordova-iad-pro

**Comment by vespino** [comment]
I would like to, but since I'm using Phonegap Build, how can I? Why not just fix this issue?

**Comment by floatinghotpot** [comment]
in your config.xml, write:
```xml
<gap:plugin name="com.google.cordova.iad" source="plugins.cordova.io"/>
```

the pro version has many new fatures, like full screen interstitial ad, and compatible with other ad pro plugins. with same api interface, you can also switch to other ad plugin easily.

as the pro version is better, the old iad plugin almost not maintained for quite some time.

**Comment by vespino** [comment]
Thanks, I will give it a go!

**Comment by vespino** [comment]
Now using this:

<gap:plugin name="com.rjfun.cordova.iad" source="plugins.cordova.io"/>

And this:

if(iAd) iAd.createBanner( {
			position:iAd.AD_POSITION.BOTTOM_CENTER, 
			autoShow:true
		} );

Same issue.

**Comment by floatinghotpot** [comment]
add one more option: ```offsetTopBar:true```

**Comment by vespino** [comment]
That solved the header issue, but now most of the time the iAd does not show.

**Comment by floatinghotpot** [comment]
## Notice

This plugin will not be updated any more.

Please use the pro version instead, which is much better and supports both banner and interstitial iAd.
- git repo: [https://github.com/floatinghotpot/cordova-iad-pro](https://github.com/floatinghotpot/cordova-iad-pro)
- plugin id: `com.rjfun.cordova.iad`
