### ISSUE TITLE
Hide iAd

### ISSUE THREAD

**Issue by braianj** [floatinghotpot/cordova-plugin-iad#27]
Hello, i just add the banner, but i need to hide the iAd when i need it.
is it possible?

regards

**Comment by floatinghotpot** [comment]
Yes, but I strongly recommend you use iAd pro. httpd://github.com/floatinghotpot/cordova-iAd-pro

**Comment by braianj** [comment]
Hello floatinghotpot, i've made the steps to verify the plugin

cordova create test1 com.rjfun.test1 test1;
cd test1;
cordova platform add ios;
cordova plugin add com.rjfun.cordova.iad;
rm -r www/*;
cp -r plugins/com.rjfun.cordova.iad/test/* www/;
cordova prepare;
cordova run ios;

but it return this error:

Error: ios-deploy was not found. Please download, build and install version 1.2.0 or greater from https://github.com/phonegap/ios-deploy into your path. Or 'npm install -g ios-deploy' using node.js: http://nodejs.org/
ERROR running one or more of the platforms: Error: /Users/.../test1/platforms/ios/cordova/run: Command failed with exit code 1
You may not have the required environment or OS to run this project

So i run cordova build ios and ** BUILD SUCCEEDED **

but, inside my real project, when I install the plugin and run cordova build it said

ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build/emulator/Diam.app/Diam normal i386
(1 failure)
ERROR building one of the platforms: Error: /Users/.../Diam/Repositorio/diam/platforms/ios/cordova/build: Command failed with exit code 65
You may not have the required environment or OS to build this project

so the strongly recommended doesn't work for me. What should i do?

**Comment by floatinghotpot** [comment]
Please upgrade your Xcode to latest version, and upgrade cordova and ios-deploy to latest version

sudo npm install -g cordova
sudo npm install -g ios-deploy

**Comment by braianj** [comment]
Thanks for your incredible fast response.
i have xCode Version 6.1.1 (6A2008a)
And cordova 4.2
i made sudo npm install -g ios-deploy just in case, but still the error when build my project

Undefined symbols for architecture i386:
  "_ADBannerContentSizeIdentifierLandscape", referenced from:
      -[iAdPlugin __createAdView:] in iAdPlugin.o
      -[iAdPlugin onOrientationChange] in iAdPlugin.o
  "_ADBannerContentSizeIdentifierPortrait", referenced from:
      -[iAdPlugin __createAdView:] in iAdPlugin.o
      -[iAdPlugin onOrientationChange] in iAdPlugin.o
  "_OBJC_CLASS_$_ADBannerView", referenced from:
      objc-class-ref in iAdPlugin.o
  "_OBJC_CLASS_$_ADInterstitialAd", referenced from:
      objc-class-ref in iAdPlugin.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build/emulator/Diam.app/Diam normal i386
(1 failure)
ERROR building one of the platforms: Error: /Users/.../Diam/Repositorio/diam/platforms/ios/cordova/build: Command failed with exit code 65
You may not have the required environment or OS to build this project

**Comment by braianj** [comment]
Run again the test on the plugin page and ios-deploy close suddenly

Process:               ios-deploy [3946]
Path:                  /usr/local/lib/node_modules/ios-deploy/ios-deploy
Identifier:            ios-deploy
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        bash [3775]
Responsible:           Terminal [2095]
User ID:               501

Date/Time:             2015-02-27 02:02:21.974 -0300
OS Version:            Mac OS X 10.10.3 (14D72i)
Report Version:        11

Time Awake Since Boot: 22000 seconds
Time Since Wake:       5200 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000

**Comment by floatinghotpot** [comment]
it seems some lib is missing when linking. Please check and make sure iAd.framework is added to the project.

**Comment by braianj** [comment]
bang! nice shot. It works perfect now. I need to analice your example for more functions details but now, maybe you can help me in this, and i can help you too, the plugin has a lot of warnings.
![captura de pantalla 2015-02-27 a las 3 58 55](https://cloud.githubusercontent.com/assets/6572776/6408527/017c0742-be35-11e4-99dd-b20327e51d72.png)

**Comment by floatinghotpot** [comment]
Yes, some old and deprecated APIs are called, will cause some warning but still works. Will port the code to new APIs later when find time.

**Comment by braianj** [comment]
Thanks for all your help! really appreciated!
